// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { join } from "path";
import "dotenv/config";
import { defineConfig } from "prisma/config";
import {config} from 'dotenv'
//Load config
config({
  path: '.env'
})

export default defineConfig({
  schema: join(__dirname, 'prisma', 'models'),
  migrations: {
    seed: "bun prisma/seed/index.ts", 
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
